local_database_host: "cosmos-db-midgard"
local_database_port: "5432"
local_database_name: "development"
local_database_user: "db"
local_database_pass: "db"
 
test_database_host: "cosmos-db-midgard-test"
test_database_port: "5433"
test_database_name: "test"
test_database_user: "test"
test_database_pass: "test"

LOG_LEVEL: "debug"

REDIS_URL: "redis://:root123@redis:6379"
REDIS_CACHE_PATH: "0/cache"