version: "3"
services:
  cosmos-db-midgard-test:
    image: "postgres:13"
    container_name: "cosmos-db-midgard-test"
    restart: always
    tty: true
    environment:
        POSTGRES_DB: test
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
    ports:
        - 5432:5432
    command: -p 5432
    networks:
        - cosmos_network

  cosmos-midgard:
    image: matheuscatalan123/cosmos-midgard:latest
    container_name: "cosmos-midgard"
    entrypoint: "dockerize -template .docker/application.yml:config/application.yml  
                          ./.docker/docker-entrypoint.sh"
    restart: on-failure
    volumes:
      - ./services/midgard:/usr/src/app
    ports:
      - "8181:8080"
    networks:
      - cosmos_network

networks:
  cosmos_network:
    driver: bridge